name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f62be853174d353b6a1437b9be55b433598bf70160347300db819365f00e395"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
