name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e1a4ab586481acd3f843bcc6d24a00f04b9264b35fe5478f69fdfa53817916c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
