name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c70a52021d59ef2baa8b1788f7dd0e495e0c0959d7de0d5f9a83113d91965992"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
