name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e155b440667ba8fcf0c233f21421d8a4cc7aee2bda8202a16b1192f476ad2cd9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
