name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6874df83adc01bf2cca39edc33238bb4790a55a0e14840618549d0609cd16551"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
