name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f57a9e384a944e9ea84001ae2a27d0221474c95bffbf8d45accb64dd143fe961"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
