name = "Minecraft Modpack"
author = "sajenim"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d2f062a37eaede04a077deb0f013fb2bba5d00a9a2ef3e025d4907ba0b57b07"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
